services:
  postgres:
    image: postgres:16-alpine
    container_name: parabellum-postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
