version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: payload_postgres
    restart: always
    environment:
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload123
      POSTGRES_DB: payloaddb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
